### ISSUE TITLE
cant connect server 199.59.149.236:443

### ISSUE THREAD

**Issue by mmm141023** [jasp402/Easy-YOPmail#13]
Error: connect ETIMEDOUT 199.59.149.236:443
getMail(): Error getting YOPMail page
connect ETIMEDOUT 199.59.149.236:443
node:internal/process/promises:279

**Comment by jasp402** [comment]
![image](https://github.com/jasp402/Easy-YOPmail/assets/8978470/da514e4b-3d9c-4133-a31f-447e46b2eba8)

You don't provide much context. You may be trying to run it from a "pod" of Kubernete or Dockers and have a network problem in the service you created. But the Easy-YOPmail service is operational. You can validate it

pasting this code:

```
easyYopmail.getMail().then(mail=>{
     console.log(mail);
})
```

at [https://npm.runkit.com/easy-yopmail](https://npm.runkit.com/easy-yopmail)


This ticket is closed.
