### ISSUE TITLE
Attached files in read message

### ISSUE THREAD

**Issue by ArthurGlacetAdeo** [jasp402/Easy-YOPmail#14]
Hello,

It seems to me that the readMessage function does not return attached files. it would be nice to be able to get thoses as well.
The link of the attached file is present on the mail and then be able to download it.

**Comment by jasp402** [comment]
Hello, it is an improvement that we are working on to be included in version 5. Along with the possibility of obtaining the images that come in the emails.

I am going to leave this ticket open until version 5 is released and validate that this option works correctly. Thank you for using Easy-YOPmail

**Comment by ArthurGlacetAdeo** [comment]
finally had time to test it!

it works fine but i can't download the file using a simple get as it returns an HTTP400 due to the lack of cookies...
Could you add a way to download the attachement ?

**Comment by jasp402** [comment]
I am glad to know that you have been able to use it.

At the time, I made a test circuit; however, it is possible that I did not have a test case like yours. Please share your test case with us so we can try to replicate it.

As I mentioned earlier, I was only able to test with small files in PDF and ZIP formats.

**Comment by ArthurGlacetAdeo** [comment]
i just try to download a pdf attached file. if i follow a attachement file dowload URL from a incognito browser i'm getting an HTTP400.

Same if a make a get api call.

**Comment by jasp402** [comment]
I'm going to be revisiting this case this week.
Since it's an API, the correct thing to do would be to return the binary. However, this represents a security breach, as I have no way of identifying malicious code.

The short cut is to download the file locally where the project is running and make the path available.
And since there is a risk, the user must activate the getAttachment option so that the attached content can be included.

**Comment by iam-alex-p** [comment]
Thank you for adding this feature, @jasp402 
I was able to get an attachments object with filename, path and extension.

However, when I am trying to download .PDF attachment using commons-io Java Library or performing GET request in Postman or try to access URL from browsers Incognito Mode, I am experiencing HTTP Error 400.

Please, find attachments object, I use for testing, below:

`{
   "fullName":"sample.pdf",
   "name":"sample",
   "extension":"pdf",
   "file":"https://yopmail.com//cid?b=a.p.testing.email.address&id=e_ZwDjBGR5ZwN0BQR4ZQNkZwZlAGpkZt==&cd=a&pj=f_m19rk5tr0"
}`

It seems like file is downloaded successfully when I am in non-incognito mode in Chrome Browser.

Could you please recommend the way how to download attached file programmatically using the link provided via Easy-YOPmail?

<img width="1019" alt="AttachmentError" src="https://github.com/user-attachments/assets/0d9fa33a-f8de-4643-b479-aa44dfb3b58e">

**Comment by iam-alex-p** [comment]
@jasp402 could you please share the test case or snipped of code, which you used to test downloading attachments from the email?

I am using following code to download .pdf attachment using link from **attachments.file** section of **readMessage** response. I basically get the same HTTP 400 Error response, but in form of a file. Is downloading attachments functionality supposed to work in EasyYOPmail v5.1.0?

`export function getEmailAttachment(from, messageId) {
    easyYopmail.readMessage(from, messageId).then(function(response) {
        if (response.attachments) {
            const ATTACHMENT = response.attachments;
            console.log(ATTACHMENT.file);
            const URL = ATTACHMENT.file;
            
            https.get(URL, (res) => {
                const PATH = ATTACHMENT.fullName;
                const WRITE_STREAM = fs.createWriteStream(PATH);

                res.pipe(WRITE_STREAM);

                WRITE_STREAM.on("finish", () => {
                    WRITE_STREAM.close();
                    console.log("Download Completed");
                });
            });
        } else {
            console.log(null);
        }
    });
}`

**Comment by ArthurGlacetAdeo** [comment]
> I'm going to be revisiting this case this week. Since it's an API, the correct thing to do would be to return the binary. However, this represents a security breach, as I have no way of identifying malicious code.
> 
> The short cut is to download the file locally where the project is running and make the path available. And since there is a risk, the user must activate the getAttachment option so that the attached content can be included.

Hello @jasp402, did you had time to check on this ?
