### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by StephenMP** [jasp402/Easy-YOPmail#18]
It looks like v4.x used to be written in JS on the master branch as the source of truth. Now it seems that it's being developed locally on a private branch as the source of truth and you have local scripts that minify the JS and push it to the main branch.

If I wanted to contribute, how can I do so since I can't code against the minified JS?

**Comment by jasp402** [comment]
Hello. If correct, the public version is obfuscated to improve performance and minimize weight. The way the community has been participating and helping to improve the bookstore with their experience and use. For example, version 5.1 was released today to meet a need raised by the community.

Do you have any particular improvements you'd like to see in the library?

**Comment by StephenMP** [comment]
@jasp402 

Yes, I understand the minification, I was just hoping to have a way in which to contribute (e.g. a dev branch that is non-minified). Changes I was hoping to PR was obtaining available domains including the daily domain as well as adding type support for TypeScript, etc.
