### ISSUE TITLE
Issue with reading email

### ISSUE THREAD

**Issue by this-is-space** [jasp402/Easy-YOPmail#21]
It always says invalid email id it's not working anymore

**Comment by jasp402** [comment]
Hi. I would love to help you, can you provide more information? What email do you want to read? What is the code you are implementing? How can the error you mention be replicated?

Help me with that information and I will be carrying out a detailed review of the error.

**Comment by this-is-space** [comment]
I figured it out

String Should be In Complete lower case to access the main
