### ISSUE TITLE
readMessage not working

### ISSUE THREAD

**Issue by RealByron** [jasp402/Easy-YOPmail#25]
```
const easyYopmail = require('./index.js');

easyYopmail.getInbox('test@yopmail.com')
.then(inbox => {
  const emailId = inbox.inbox[0].id;

  easyYopmail.readMessage('test@yopmail.com', emailId, { format: 'HTML' })
  .then(message => {
      console.log(message.content); // HTML content of the email
  });
});
```

simple test generates this output :
```
node test.js 
C:\DevGit\Easy-YOPmail\src\core.js:427
      new Error(b))
      ^

Error: Error getting cookies
 - Error getting cookies
    at EasyYopmail.handleError (C:\DevGit\Easy-YOPmail\src\core.js:427:7)
    at EasyYopmail.getHttpSettings (C:\DevGit\Easy-YOPmail\src\core.js:198:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EasyYopmail.getInbox (C:\DevGit\Easy-YOPmail\index.js:29:11)

Node.js v22.5.1
```

**Comment by jasp402** [comment]
Hi guys, I have done several tests using the tool [https://replit.com/@jasp402/Testing-EasyYopmail](https://replit.com/@jasp402/Testing-EasyYopmail) and I see that it is operational. I also decided to re-run the application tests to validate if something was broken. But all the tests have passed without problem.

If you could share with me the code fragment that you are running. Maybe I could help or if you have an example case with which I can validate myself. I would appreciate it.

![image](https://github.com/user-attachments/assets/c8ab59be-dcc5-495d-a9ec-83d4bcdb7b6a)

**Comment by RealByron** [comment]
Oh you're right, and get cookies seems to be relevant to recaptcha barrier. you can close this issue
