### ISSUE TITLE
Yopmail- Sender object info is shown in Subject and Subject info shown in content , no way to access mail body

### ISSUE THREAD

**Issue by Vinodkomeershetty** [jasp402/Easy-YOPmail#3]
![image](https://user-images.githubusercontent.com/7869073/142811045-6d97bf36-2dfe-49e0-91e1-e46256f2084e.png)

Sample Snippet

// const constants   = require('../constants/constants.app');
const easyYopmail = require('easy-yopmail');
// const assert      = require('assert');
// const fs          = require('fs');

const k= async function(){
    const    inbox = await easyYopmail.getInbox("abc@yopmail.com", {}, {MAX_PAGE:1});
//Below code is not working
    // const    inbox1 = await easyYopmail.readMessage("abc@yopmail.com");
    await console.log(JSON.stringify(inbox))
    // await console.log(JSON.stringify(inbox1))
    // await console.log(inbox1)
    // await console.log(inbox1)
    }

    k();

**Comment by Vinodkomeershetty** [comment]
I am not able to find a way to read the message of the emails, can you please help me out how to acheive

**Comment by jasp402** [comment]
use the inbox to get the _id of the mail you want to read.
use the second parameter to filter by **subject** or **content**

```js
const easyYOPmail = require('easy-yopmail');
easyYOPmail.inbox('abc@yopmail.com').then(inbox=>{
 	console.log(inbox);
});
```

```
//respuesta
/*
[
    {
      id: 'e_ZwRkZGV5ZQNmAQZ4ZQNjZQR5BGH3BN==',
      time: '19:34',
      subject: 'insightalertstest@gmail.com',
      content: 'Daily Statistics For Portal: hi'
    },
    {
      id: 'e_ZwRkZGV5ZQNmAQZ1ZQNjZQR5BGV4ZD==',
      time: '19:34',
      subject: 'insightalertstest@gmail.com',
      content: 'ポータルの日次統計: どういたしまして'
    },
    {
      id: 'e_ZwRkZGV5ZQNmAQV4ZQNjZQR5BQp1ZD==',
      time: '19:34',
      subject: 'insightalertstest@gmail.com',
      content: 'Daily Statistics For Portal: Insight'
    },
    {
      id: 'e_ZwRkZGV5ZQNmAQV0ZQNjZQR5BQD2BN==',
      time: '19:34',
      subject: 'insightalertstest@gmail.com',
      content: 'Daily Statistics For Portal: maint beta'
    },
    {
      id: 'e_ZwRkZGV5ZQNmAQR4ZQNjZQR5BQRmZt==',  <-------------------------- USE THIS ID
      time: '19:34',
      subject: 'Lee Arnold', <-------------------------------------------------------------- READ THIS!
      content: 'I want to send you your money back'
    }
]
*/
```

```js
easyYOPmail.readMessage('abc@yopmail.com', 'e_ZwRkZGV5ZQNmAQR4ZQNjZQR5BQRmZt==').then(mail => {
	console.log(mail)
});
```

reading an email generates a default HTML file (see image)
![image](https://user-images.githubusercontent.com/8978470/143793435-030f907f-96a5-4b17-a194-706de1663ac7.png)
result
![image](https://user-images.githubusercontent.com/8978470/143793513-2830701a-2049-437a-98bc-2a20f80272cb.png)

But you can get just the text content or you can use HTML selectors to extract a specific section.
You can review the documentation at
https://jasp402.gitbook.io/easy-yopmail/methods/messages/read-message-1
![image](https://user-images.githubusercontent.com/8978470/143793674-48ca4bc5-7c18-474e-81c4-c23837eeb465.png)

If the information is not enough or you have any other problem, do not hesitate to consult.
