### ISSUE TITLE
getInbox(): Error getting Inbox page for simple call

### ISSUE THREAD

**Issue by younes-zeboudj** [jasp402/Easy-YOPmail#7]
## 🐛 **Issue Report**

**Title:** [Short and descriptive title]

**Labels:** bug

**Environment:**

* Operating system: 💻  Ubuntu
* Version of NodeJS: 🌐 20.2.0
* Version of Easy-yopmail: 📦 ^4.0.17

<hr>

**Steps to Reproduce:**

1. ➡️ **[Step 1]**
This code is sufficient to reproduce:

```
const easyYOPmail = require('easy-yopmail');

easyYOPmail.getInbox('nauprarabratri-5567@yopmail.com').then(inbox => {
    console.log(inbox);
})
```

The email exists, it was created with the current API.
<hr>

🏳️ **Expected Behavior:**
inbox gets fetched

🚩 **Actual Behavior:**
Error:
```
getInbox(): Error getting Inbox page

Request failed with status code 403
```

**Comment by jasp402** [comment]
We appreciate your report and we apologize if you have experienced inconveniences with the use of EasyYopmail.

I have validated your code and tested it in the tool provided by NPM and it works normally.
https://npm.runkit.com/easy-yopmail

![image](https://github.com/jasp402/Easy-YOPmail/assets/8978470/599dccfc-883b-45e6-b9f0-cbefe183952b)

We must clarify that the availability and operation of EasyYopmail depend directly on the [YOPmail](https://yopmail.com/) service. Therefore, there may be times when this service is not available, which could cause errors. In addition, you may find yourself with a captcha that you need to solve to continue using the service, depending on the number of requests you are making. Please note that these situations are beyond our control and we recommend taking appropriate measures.

In case you encounter these problems, we suggest the following steps:

1) Check the status of Yopmail: You can do it by visiting its main page and checking if there are any error or maintenance messages. And entering the email you want to check from the official portal.

2) Moderate the frequency of your queries: If you are seeing captchas frequently, we suggest that you try to reduce the number of queries you make in a short period of time.

We appreciate your patience and understanding as we work through these challenges inherent in interacting with external services like EasyYopmail.
