### ISSUE TITLE
How to bypass google captcha to get mail list?

### ISSUE THREAD

**Issue by er-vinhlv** [jasp402/Easy-YOPmail#9]
Title: How to bypass google captcha to get mail list?

About: Suggest an idea for this project

**Comment by jasp402** [comment]
Sorry for the delay in responding. Can you give more context to the problem? Easy-Yopmail uses request, generally avoids any captcha validation until the last update works without any captcha notification being displayed.

If you have a screenshot or an example that I can reproduce for sure, I could work on improving this aspect.

**Comment by jasp402** [comment]
This issue is closed due to lack of activity.
